/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graphit;

/**
 *
 * @author admin
 */
public class FuncBuilder extends javax.swing.JPanel {

    /**
     * Creates new form FuncBuilder
     */
    public FuncBuilder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonParam = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonX = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        buttonTimes = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonDivided = new javax.swing.JButton();
        buttonSin = new javax.swing.JButton();
        buttonCos = new javax.swing.JButton();
        buttonTan = new javax.swing.JButton();
        buttonLn = new javax.swing.JButton();
        buttonSec = new javax.swing.JButton();
        buttonCsc = new javax.swing.JButton();
        buttonCot = new javax.swing.JButton();
        buttonExp = new javax.swing.JButton();
        buttonAsin = new javax.swing.JButton();
        buttonAcos = new javax.swing.JButton();
        buttonAtan = new javax.swing.JButton();
        buttonPowerOfX = new javax.swing.JButton();
        buttonAsec = new javax.swing.JButton();
        buttonAcsc = new javax.swing.JButton();
        buttonAcot = new javax.swing.JButton();
        buttonPowerOfE = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(8, 0));

        buttonParam.setText("a");
        add(buttonParam);

        button0.setText("0");
        add(button0);

        buttonX.setText("<html><i>x</i></html>");
        add(buttonX);

        buttonPlus.setText("+");
        add(buttonPlus);

        button1.setText("1");
        add(button1);

        button2.setText("2");
        add(button2);

        button3.setText("3");
        add(button3);

        buttonMinus.setText("-");
        add(buttonMinus);

        button4.setText("4");
        add(button4);

        button5.setText("5");
        add(button5);

        button6.setText("6");
        add(button6);

        buttonTimes.setText("*");
        add(buttonTimes);

        button7.setText("7");
        add(button7);

        button8.setText("8");
        add(button8);

        button9.setText("9");
        add(button9);

        buttonDivided.setText("/");
        add(buttonDivided);

        buttonSin.setText("sin");
        add(buttonSin);

        buttonCos.setText("cos");
        add(buttonCos);

        buttonTan.setText("tan");
        add(buttonTan);

        buttonLn.setText("ln");
        add(buttonLn);

        buttonSec.setText("sec");
        add(buttonSec);

        buttonCsc.setText("csc");
        add(buttonCsc);

        buttonCot.setText("cot");
        add(buttonCot);

        buttonExp.setText("exp");
        add(buttonExp);

        buttonAsin.setText("Asin");
        add(buttonAsin);

        buttonAcos.setText("Acos");
        add(buttonAcos);

        buttonAtan.setText("Atan");
        add(buttonAtan);

        buttonPowerOfX.setText("<html><i>x</i><sup>y</sup></html>");
        add(buttonPowerOfX);

        buttonAsec.setText("Asec");
        add(buttonAsec);

        buttonAcsc.setText("Acsc");
        add(buttonAcsc);

        buttonAcot.setText("Acot");
        add(buttonAcot);

        buttonPowerOfE.setText("<html>e<sup>y</sup></html>");
        add(buttonPowerOfE);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAcos;
    private javax.swing.JButton buttonAcot;
    private javax.swing.JButton buttonAcsc;
    private javax.swing.JButton buttonAsec;
    private javax.swing.JButton buttonAsin;
    private javax.swing.JButton buttonAtan;
    private javax.swing.JButton buttonCos;
    private javax.swing.JButton buttonCot;
    private javax.swing.JButton buttonCsc;
    private javax.swing.JButton buttonDivided;
    private javax.swing.JButton buttonExp;
    private javax.swing.JButton buttonLn;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonParam;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonPowerOfE;
    private javax.swing.JButton buttonPowerOfX;
    private javax.swing.JButton buttonSec;
    private javax.swing.JButton buttonSin;
    private javax.swing.JButton buttonTan;
    private javax.swing.JButton buttonTimes;
    private javax.swing.JButton buttonX;
    // End of variables declaration//GEN-END:variables
}
