/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graphit;

import java.awt.Color;

/**
 *
 * @author Scott Meyer
 */
public class GraphItGUI extends javax.swing.JFrame {

    /**
     * Creates new form GraphItGUI
     */
    public GraphItGUI() {
        color = Color.red;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        controlPanel = new javax.swing.JPanel();
        formulaBox = new javax.swing.JComboBox();
        formulaLabel = new javax.swing.JLabel();
        paramLabelA = new javax.swing.JLabel();
        paramFieldA = new javax.swing.JTextField();
        paramSliderA = new javax.swing.JSlider();
        paramLabelB = new javax.swing.JLabel();
        paramFieldB = new javax.swing.JTextField();
        paramSliderB = new javax.swing.JSlider();
        paramLabelC = new javax.swing.JLabel();
        paramFieldC = new javax.swing.JTextField();
        paramSliderC = new javax.swing.JSlider();
        paramLabelD = new javax.swing.JLabel();
        paramFieldD = new javax.swing.JTextField();
        paramSliderD = new javax.swing.JSlider();
        paramLabelE = new javax.swing.JLabel();
        paramFieldE = new javax.swing.JTextField();
        paramSliderE = new javax.swing.JSlider();
        resetButton = new javax.swing.JButton();
        mainGraphPanel = new GraphPanel.GraphPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        formulaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sine", "Cosine", "Tangent", "Secant", "Cosecant", "Cotangent", "Arcsine", "Arccosine", "Arctangent", "Arcsecant", "Arccosecant", "Arccotangent" }));
        formulaBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formulaBoxAncestorRemoved(evt);
            }
        });
        formulaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulaBoxActionPerformed(evt);
            }
        });
        formulaBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formulaBoxPropertyChange(evt);
            }
        });

        formulaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formulaLabel.setText("<html><i>y</i> = asinb<i>x</i></html>");

        paramLabelA.setText("a:");

        paramFieldA.setEditable(false);
        paramFieldA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paramFieldA.setText("1");

        paramSliderA.setMinimum(-100);
        paramSliderA.setValue(1);
        paramSliderA.setEnabled(false);
        paramSliderA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                paramSliderAStateChanged(evt);
            }
        });

        paramLabelB.setText("b:");

        paramFieldB.setEditable(false);
        paramFieldB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paramFieldB.setText("1");

        paramSliderB.setMinimum(-100);
        paramSliderB.setValue(1);
        paramSliderB.setEnabled(false);
        paramSliderB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                paramSliderBStateChanged(evt);
            }
        });

        paramLabelC.setText("c:");

        paramFieldC.setEditable(false);
        paramFieldC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paramFieldC.setText("1");

        paramSliderC.setMinimum(-100);
        paramSliderC.setValue(1);
        paramSliderC.setEnabled(false);
        paramSliderC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                paramSliderCStateChanged(evt);
            }
        });

        paramLabelD.setText("d:");

        paramFieldD.setEditable(false);
        paramFieldD.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paramFieldD.setText("1");

        paramSliderD.setMinimum(-100);
        paramSliderD.setValue(1);
        paramSliderD.setEnabled(false);
        paramSliderD.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                paramSliderDStateChanged(evt);
            }
        });

        paramLabelE.setText("e:");

        paramFieldE.setEditable(false);
        paramFieldE.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paramFieldE.setText("1");

        paramSliderE.setMinimum(-100);
        paramSliderE.setValue(1);
        paramSliderE.setEnabled(false);
        paramSliderE.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                paramSliderEStateChanged(evt);
            }
        });

        resetButton.setText("Reset");

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formulaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formulaLabel)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(paramLabelA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paramFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(paramLabelB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paramFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(paramLabelC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paramFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(paramLabelD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paramFieldD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(paramLabelE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paramFieldE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paramSliderA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paramSliderB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paramSliderC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paramSliderD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paramSliderE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addGap(67, 67, 67))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formulaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formulaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramLabelA)
                    .addComponent(paramFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramSliderA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramLabelB)
                    .addComponent(paramFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramSliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramLabelC)
                    .addComponent(paramFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramSliderC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramLabelD)
                    .addComponent(paramFieldD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramSliderD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramLabelE)
                    .addComponent(paramFieldE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramSliderE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainGraphPanelLayout = new javax.swing.GroupLayout(mainGraphPanel);
        mainGraphPanel.setLayout(mainGraphPanelLayout);
        mainGraphPanelLayout.setHorizontalGroup(
            mainGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        mainGraphPanelLayout.setVerticalGroup(
            mainGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formulaBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formulaBoxPropertyChange
            
    }//GEN-LAST:event_formulaBoxPropertyChange

    private void paramSliderAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_paramSliderAStateChanged
        paramFieldA.setText( Integer.toString(paramSliderA.getValue()) );
        form.setA( paramSliderA.getValue() );
    }//GEN-LAST:event_paramSliderAStateChanged

    private void paramSliderBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_paramSliderBStateChanged
        paramFieldB.setText( Integer.toString(paramSliderB.getValue()) );
        form.setB( paramSliderA.getValue() );
    }//GEN-LAST:event_paramSliderBStateChanged

    private void paramSliderCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_paramSliderCStateChanged
        paramFieldC.setText( Integer.toString(paramSliderC.getValue()) );
        form.setC( paramSliderC.getValue() );
    }//GEN-LAST:event_paramSliderCStateChanged

    private void paramSliderDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_paramSliderDStateChanged
        paramFieldD.setText( Integer.toString(paramSliderD.getValue()) );
        form.setD( paramSliderD.getValue() );
    }//GEN-LAST:event_paramSliderDStateChanged

    private void paramSliderEStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_paramSliderEStateChanged
        paramFieldE.setText( Integer.toString(paramSliderE.getValue()) );
        form.setE( paramSliderE.getValue() );
    }//GEN-LAST:event_paramSliderEStateChanged

    private void formulaBoxAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formulaBoxAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formulaBoxAncestorRemoved

    private void formulaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulaBoxActionPerformed
        switch( formulaBox.getSelectedIndex() ) {
            case 0: form = new Sin( new double[] { 1.0, 1.0 } );
                    break;
            case 1: form = new Cos( new double[] { 1.0, 1.0 } );
                    break;
            case 2: form = new Tan( new double[] { 1.0, 1.0 } );
                    break;
            case 3: form = new Sec( new double[] { 1.0, 1.0 } );
                    break;
            case 4: form = new Csc( new double[] { 1.0, 1.0 } );
                    break;
            case 5: form = new Cot( new double[] { 1.0, 1.0 } );
                    break;
            /*case 6: form = new Asin( new double[] { 1.0, 1.0 } );
                    break;
            case 7: form = new Acos( new double[] { 1.0, 1.0 } );
                    break;
            case 8: form = new Atan( new double[] { 1.0, 1.0 } );
                    break;
            case 9: form = new Asec( new double[] { 1.0, 1.0 } );
                    break;
            case 10: form = new Acsc( new double[] { 1.0, 1.0 } );
                    break;
            case 11: form = new Acot( new double[] { 1.0, 1.0 } );
                    break;*/
        }
        formulaLabel.setText( form.getLabel() );
        form.setColor( color );
        
        paramSliderA.setEnabled( false );
        paramSliderB.setEnabled( false );
        paramSliderC.setEnabled( false );
        paramSliderD.setEnabled( false );
        paramSliderE.setEnabled( false );
        
        switch( form.getParams().length ) {
            case 5: paramSliderE.setEnabled( true );
            case 4: paramSliderD.setEnabled( true );
            case 3: paramSliderC.setEnabled( true );
            case 2: paramSliderB.setEnabled( true );
            case 1: paramSliderA.setEnabled( true );
        }
        
        mainGraphPanel.setGraphing( true );
        mainGraphPanel.setFormula( form );
        
    }//GEN-LAST:event_formulaBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphItGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphItGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphItGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphItGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphItGUI().setVisible(true);
            }
        });
    }

    private Formula form;
    private Color color;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JComboBox formulaBox;
    private javax.swing.JLabel formulaLabel;
    private javax.swing.JToolBar jToolBar1;
    private GraphPanel.GraphPanel mainGraphPanel;
    private javax.swing.JTextField paramFieldA;
    private javax.swing.JTextField paramFieldB;
    private javax.swing.JTextField paramFieldC;
    private javax.swing.JTextField paramFieldD;
    private javax.swing.JTextField paramFieldE;
    private javax.swing.JLabel paramLabelA;
    private javax.swing.JLabel paramLabelB;
    private javax.swing.JLabel paramLabelC;
    private javax.swing.JLabel paramLabelD;
    private javax.swing.JLabel paramLabelE;
    private javax.swing.JSlider paramSliderA;
    private javax.swing.JSlider paramSliderB;
    private javax.swing.JSlider paramSliderC;
    private javax.swing.JSlider paramSliderD;
    private javax.swing.JSlider paramSliderE;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
