/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graphit;

import GraphPanel.Function;


/**
 *
 * @author admin
 */
public class ParamSlider extends javax.swing.JPanel {

    /**
     * Creates new form ParamSlider
     */
    public ParamSlider() {
        function = new Constant();
        index = 0;
        initComponents();
    }
    
    public ParamSlider( Function newFunc, int newIndex ) {
        function = newFunc;
        index = newIndex;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paramLabel = new javax.swing.JLabel();
        paramField = new javax.swing.JTextField();
        paramSlider = new javax.swing.JSlider();

        paramLabel.setText(" :");

        paramField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paramField.setText("0.0");
        paramField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramFieldActionPerformed(evt);
            }
        });

        paramSlider.setMaximum(10000);
        paramSlider.setMinimum(-10000);
        paramSlider.setValue(0);
        paramSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                paramSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paramSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paramLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paramField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramLabel)
                    .addComponent(paramField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(paramSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void paramSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_paramSliderStateChanged
        double temp = paramSlider.getValue() / 1000f;
        paramField.setText( Double.toString( temp ) );
        function.setParam( index, temp);
    }//GEN-LAST:event_paramSliderStateChanged

    private void paramFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramFieldActionPerformed
        Double temp = new Double ( paramField.getText() );
        paramSlider.setValue( (int)( temp * 1000f ) );
        function.setParam( index, temp.doubleValue() );
    }//GEN-LAST:event_paramFieldActionPerformed

    public void setFunction( Function newForm ) {
        function = newForm;
    }
    
    public Function getFunction() {
        return function;
    }
    
    public void setIndex( int newIndex ) {
        index = newIndex;
    }
    
    public int getIndex() {
        return index;
    }
    
    public void setLabel( String label ) {
        paramLabel.setText( label + ":" );
    }
    
    private GraphPanel.Function function;
    private int index;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField paramField;
    private javax.swing.JLabel paramLabel;
    private javax.swing.JSlider paramSlider;
    // End of variables declaration//GEN-END:variables
}
