package graphit;

import graphpanel.*;
import java.util.ArrayList;
import org.springframework.stereotype.Component;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */

@Component
public class FunctionBuilderDialog extends javax.swing.JDialog{

    private ArrayList<Parameter> parameters;
    private ArrayList<FunctionFramework> functions;
    private int index;
    
    /**
     * Creates new form FunctionBuilderDialog
     */
    
    public FunctionBuilderDialog() {
        
    }
    
    public FunctionBuilderDialog(java.awt.Frame parent, boolean modal, ArrayList<Parameter> newparam, ArrayList<FunctionFramework> newfunc ) {
        super(parent, "Function Builder", modal);
        initComponents();
        index = 0;
        parameters = newparam;
        functions = newfunc;
        functions.add( new FunctionFramework( (a,b) -> 0.0, (a,b) -> "0.0" ) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numField = new javax.swing.JTextField();
        functionLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonX = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonDecimal = new javax.swing.JButton();
        buttonParameter = new javax.swing.JButton();
        buttonParen = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        buttonTimes = new javax.swing.JButton();
        buttonDividedBy = new javax.swing.JButton();
        buttonLn = new javax.swing.JButton();
        buttonPower = new javax.swing.JButton();
        buttonExp = new javax.swing.JButton();
        buttonSin = new javax.swing.JButton();
        buttonCos = new javax.swing.JButton();
        buttonTan = new javax.swing.JButton();
        buttonSec = new javax.swing.JButton();
        buttonCsc = new javax.swing.JButton();
        buttonCot = new javax.swing.JButton();
        buttonAsin = new javax.swing.JButton();
        buttonAcos = new javax.swing.JButton();
        buttonAtan = new javax.swing.JButton();
        buttonAsec = new javax.swing.JButton();
        buttonAcsc = new javax.swing.JButton();
        buttonAcot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        numField.setEditable(false);
        numField.setBackground(new java.awt.Color(255, 255, 255));
        numField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numField.setText("0");
        numField.setMaximumSize(new java.awt.Dimension(200, 20));
        numField.setMinimumSize(new java.awt.Dimension(200, 20));
        numField.setRequestFocusEnabled(false);
        getContentPane().add(numField);

        functionLabel.setBackground(new java.awt.Color(255, 255, 255));
        functionLabel.setForeground(new java.awt.Color(255, 255, 255));
        functionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        functionLabel.setAlignmentX(numField.getAlignmentX());
        functionLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        functionLabel.setEnabled(false);
        functionLabel.setFocusable(false);
        functionLabel.setMaximumSize(new java.awt.Dimension(200, 20));
        functionLabel.setMinimumSize(new java.awt.Dimension(200, 20));
        functionLabel.setPreferredSize(new java.awt.Dimension(12, 20));
        getContentPane().add(functionLabel);

        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        buttonX.setText("<html><i>x</i></html>");
        buttonX.setToolTipText("Variable x.  Use this button to insert the variable x.");
        buttonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXActionPerformed(evt);
            }
        });

        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonDecimal.setText(".");
        buttonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecimalActionPerformed(evt);
            }
        });

        buttonParameter.setText("a");
        buttonParameter.setToolTipText("Parameter.  Select this button to add a parameter which can be adjusted by a slider.");
        buttonParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonParameterActionPerformed(evt);
            }
        });

        buttonParen.setText("( )");
        buttonParen.setToolTipText("Parentheses.  Click this button to finalize the current inner function and go up a level in the function tree.");
        buttonParen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonParenActionPerformed(evt);
            }
        });

        buttonPlus.setText("+");
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });

        buttonMinus.setText("-");
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });

        buttonTimes.setText("*");
        buttonTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimesActionPerformed(evt);
            }
        });

        buttonDividedBy.setText("/");
        buttonDividedBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDividedByActionPerformed(evt);
            }
        });

        buttonLn.setText("ln");
        buttonLn.setToolTipText("Natural log.  Use this button to apply the natural log function to the current function.");
        buttonLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLnActionPerformed(evt);
            }
        });

        buttonPower.setText("<html><i>y</i><sup>x</sup></html>");
        buttonPower.setToolTipText("");
        buttonPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPowerActionPerformed(evt);
            }
        });

        buttonExp.setText("<html>e<sup>x</sup></html>");
        buttonExp.setToolTipText("Power of e.  Select this button to apply the Exp function to the current function.");
        buttonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExpActionPerformed(evt);
            }
        });

        buttonSin.setText("sin");
        buttonSin.setToolTipText("Sine.  Use this button to apply the sin function to the current function.");
        buttonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinActionPerformed(evt);
            }
        });

        buttonCos.setText("cos");
        buttonCos.setToolTipText("Cosine.  Use this button to apply the cos function to the current function.");
        buttonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCosActionPerformed(evt);
            }
        });

        buttonTan.setText("tan");
        buttonTan.setToolTipText("Tangent.  Use this button to apply the tan function to the current function.");
        buttonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTanActionPerformed(evt);
            }
        });

        buttonSec.setText("sec");
        buttonSec.setToolTipText("Secant.  Use this button to apply the sec function to the current function.");
        buttonSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSecActionPerformed(evt);
            }
        });

        buttonCsc.setText("csc");
        buttonCsc.setToolTipText("Cosecant.  Use this button to apply the csc function to the current function.");
        buttonCsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCscActionPerformed(evt);
            }
        });

        buttonCot.setText("cot");
        buttonCot.setToolTipText("Cotangent.  Use this button to apply the cot function to the current function.");
        buttonCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCotActionPerformed(evt);
            }
        });

        buttonAsin.setText("Asin");
        buttonAsin.setToolTipText("Arcsin.  Use this button to apply the Asin function to the current function.");
        buttonAsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAsinActionPerformed(evt);
            }
        });

        buttonAcos.setText("Acos");
        buttonAcos.setToolTipText("Arccosine.  Use this button to apply the Acos function to the current function.");
        buttonAcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcosActionPerformed(evt);
            }
        });

        buttonAtan.setText("Atan");
        buttonAtan.setToolTipText("Arctangent.  Use this button to apply the Atan function to the current function.");
        buttonAtan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtanActionPerformed(evt);
            }
        });

        buttonAsec.setText("Asec");
        buttonAsec.setToolTipText("Arcsecant.  Use this button to apply the Asec function to the current function.");
        buttonAsec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAsecActionPerformed(evt);
            }
        });

        buttonAcsc.setText("Acsc");
        buttonAcsc.setToolTipText("Arccosecant.  Use this button to apply the Acsc function to the current function.");
        buttonAcsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcscActionPerformed(evt);
            }
        });

        buttonAcot.setText("Acot");
        buttonAcot.setToolTipText("Arccotangent.  Use this button to apply the Acot function to the current function.");
        buttonAcot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonX, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonParen, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonDividedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonLn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonSec, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonCsc, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonCot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonAsin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonAcos)
                        .addGap(0, 0, 0)
                        .addComponent(buttonAtan))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonAsec)
                        .addGap(0, 0, 0)
                        .addComponent(buttonAcsc)
                        .addGap(0, 0, 0)
                        .addComponent(buttonAcot))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonX, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonParen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDividedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonLn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSec, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCsc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCot, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAsin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAcos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAsec, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAcsc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAcot, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(buttonPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAcotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcotActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> 1 / Math.atan( a ), (a, b) -> String.format( "Acot(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonAcotActionPerformed

    private void buttonAcscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcscActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> 1 / Math.acos( a ), (a, b) -> String.format( "Acsc(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonAcscActionPerformed

    private void buttonAsecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAsecActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> 1 / Math.asin( a ), (a, b) -> String.format( "Asec(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonAsecActionPerformed

    private void buttonAtanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtanActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> Math.atan( a ), (a, b) -> String.format( "Atan(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonAtanActionPerformed

    private void buttonAcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcosActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> Math.acos( a ), (a, b) -> String.format( "Acos(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonAcosActionPerformed

    private void buttonAsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAsinActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> Math.asin( a ), (a, b) -> String.format( "Asin(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonAsinActionPerformed

    private void buttonCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCotActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> 1 / Math.tan( a ), (a, b) -> String.format( "cot(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonCotActionPerformed

    private void buttonCscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCscActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> 1 / Math.cos( a ), (a, b) -> String.format( "csc(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonCscActionPerformed

    private void buttonSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSecActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> 1 / Math.sin( a ), (a, b) -> String.format( "sec(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonSecActionPerformed

    private void buttonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTanActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> Math.tan( a ), (a, b) -> String.format( "tan(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonTanActionPerformed

    private void buttonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCosActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> Math.cos( a ), (a, b) -> String.format( "cos(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonCosActionPerformed

    private void buttonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> Math.sin( a ), (a, b) -> String.format( "sin(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonSinActionPerformed

    private void buttonExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExpActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> Math.exp( a ), (a, b) -> String.format("e<sup>%s</sup>", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonExpActionPerformed

    private void buttonPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPowerActionPerformed
        TwoArgumentFunctionFramework tempfunc = new TwoArgumentFunctionFramework( (a, b) -> Math.pow(a, b), (a, b) -> String.format( "%s<sup>%s</sup>", a, b ) );
        twoArgumentButton( tempfunc );
    }//GEN-LAST:event_buttonPowerActionPerformed

    private void buttonLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLnActionPerformed
        OneArgumentFunctionFramework tempFunc = new OneArgumentFunctionFramework( ( a, b ) -> Math.log( a ), (a, b) -> String.format( "ln(%s)", a ) );
        oneArgumentButton( tempFunc );
    }//GEN-LAST:event_buttonLnActionPerformed

    private void buttonDividedByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDividedByActionPerformed
        TwoArgumentFunctionFramework tempfunc = new TwoArgumentFunctionFramework( (a,b) -> a / b, (a, b) -> String.format("%s / %s", a, b ) );
        twoArgumentButton( tempfunc );
    }//GEN-LAST:event_buttonDividedByActionPerformed

    private void buttonTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimesActionPerformed
        TwoArgumentFunctionFramework tempfunc = new TwoArgumentFunctionFramework( (a,b) -> a * b, (a, b) -> String.format("%s * %s", a, b ) );
        twoArgumentButton( tempfunc );
    }//GEN-LAST:event_buttonTimesActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
        TwoArgumentFunctionFramework tempfunc = new TwoArgumentFunctionFramework( (a,b) -> a - b, (a, b) -> String.format("%s - %s", a, b ) );
        twoArgumentButton( tempfunc );
    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        TwoArgumentFunctionFramework tempfunc = new TwoArgumentFunctionFramework( (a,b) -> a + b, (a, b) -> String.format("%s + %s", a, b ) );
        twoArgumentButton( tempfunc );
    }//GEN-LAST:event_buttonPlusActionPerformed

    private void buttonParenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonParenActionPerformed
        numField.setText("0.0");
        if( index > 0 ) index--;
    }//GEN-LAST:event_buttonParenActionPerformed

    private void buttonParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonParameterActionPerformed
        numField.setText("0.0");
        Parameter newparam = new Parameter();
        parameters.add( newparam );
        functions.get( index ).setFunction( newparam );
        int labelint = parameters.size() - 1;
        functions.get( index ).setLabel( (a,b) -> new String( Character.toChars( Character.codePointAt( new char[] { 'a' }, 0 ) + labelint ) ));
        updateFunction();
    }//GEN-LAST:event_buttonParameterActionPerformed

    private void buttonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecimalActionPerformed
        updateDigit( "." );
        updateFunction();
    }//GEN-LAST:event_buttonDecimalActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        updateDigit( "0" );
        updateFunction();
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXActionPerformed
        numField.setText("0.0");
        functions.get( index ).setFunction( ( a, b ) -> a );
        functions.get( index ).setLabel( (a, b) -> "<i>x</i>" );
        updateFunction();
    }//GEN-LAST:event_buttonXActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        updateDigit( "9" );
        updateFunction();
    }//GEN-LAST:event_button9ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        updateDigit( "8" );
        updateFunction();
    }//GEN-LAST:event_button8ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        updateDigit( "7" );
        updateFunction();
    }//GEN-LAST:event_button7ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        updateDigit( "6" );
        updateFunction();
    }//GEN-LAST:event_button6ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        updateDigit( "5" );
        updateFunction();
    }//GEN-LAST:event_button5ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        updateDigit( "4" );
        updateFunction();
    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        updateDigit( "3" );
        updateFunction();
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        updateDigit( "2" );
        updateFunction();
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        updateDigit( "1" );
        updateFunction();
    }//GEN-LAST:event_button1ActionPerformed

    private void updateDigit( String digit ) {
        numField.setText( numField.getText() + digit );
        double x = Double.parseDouble( numField.getText() );
        functions.get(index).setFunction(( a, b ) -> x);
        functions.get(index).setLabel((a, b) -> Double.toString( x ) );
        updateFunction();
    }
    
    private void updateFunction() {
        functionLabel.setText( String.format("<html><i>y</i> = %s</html>", functions.get( 0 ).getLabelText() ) );
    }
    
    private void oneArgumentButton( FunctionFramework tempFunc ) {
        numField.setText("0.0");
        tempFunc.setFramework( functions.get( index ), 0 );
        if( index >= 1 ) {
            functions.get(index - 1).replaceFramework( functions.get( index ), tempFunc );
            functions.set( index, tempFunc );
        }
        else {
            functions.set( 0, tempFunc );
        }
        updateFunction();
    }
    
    private void twoArgumentButton( FunctionFramework tempFunc ) {
        numField.setText("");
        tempFunc.setFramework( functions.get( index ), 0 );
        if( index >= 1 ) {
            functions.get(index - 1).replaceFramework( functions.get( index ), tempFunc );
            functions.set( index, tempFunc );
        }
        else {
            functions.set( 0, tempFunc );
        }
        FunctionFramework tempfunc2 = new FunctionFramework( (a, b) -> 0.0, (a, b) -> "0.0" );
        tempFunc.setFramework( tempfunc2, 1 );
        index++;
        if( functions.size() > index ) functions.set( index, tempfunc2 );
        else functions.add( tempfunc2 );
        updateFunction();
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FunctionBuilderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FunctionBuilderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FunctionBuilderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FunctionBuilderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FunctionBuilderDialog dialog = new FunctionBuilderDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAcos;
    private javax.swing.JButton buttonAcot;
    private javax.swing.JButton buttonAcsc;
    private javax.swing.JButton buttonAsec;
    private javax.swing.JButton buttonAsin;
    private javax.swing.JButton buttonAtan;
    private javax.swing.JButton buttonCos;
    private javax.swing.JButton buttonCot;
    private javax.swing.JButton buttonCsc;
    private javax.swing.JButton buttonDecimal;
    private javax.swing.JButton buttonDividedBy;
    private javax.swing.JButton buttonExp;
    private javax.swing.JButton buttonLn;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton buttonParameter;
    private javax.swing.JButton buttonParen;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonPower;
    private javax.swing.JButton buttonSec;
    private javax.swing.JButton buttonSin;
    private javax.swing.JButton buttonTan;
    private javax.swing.JButton buttonTimes;
    private javax.swing.JButton buttonX;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JTextField numField;
    // End of variables declaration//GEN-END:variables
}
